### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kovac777** [robertohuertasm/apk-decompiler#1]
Hello! I have get error

![image](https://user-images.githubusercontent.com/13153254/59044063-14f35f80-8886-11e9-839d-fe72e5f8d0d9.png)

**Comment by robertohuertasm** [comment]
Can you share the apk that you're trying to decompile or it's not possible?

**Comment by kovac777** [comment]
https://play.google.com/store/apps/details?id=by.tut.finance.android
[base.zip](https://github.com/robertohuertasm/apk-decompiler/files/3262246/base.zip)

**Comment by robertohuertasm** [comment]
Are you using OS or Linux? I've tested it in Ubuntu and it seems to be working.

**Comment by kovac777** [comment]
Ubuntu 19.04

**Comment by robertohuertasm** [comment]
Just to be clear, I tested it with the `apk` included in the `base.zip`, is that ok? I tried Ubuntu 18.04 and it worked. I'll probably have some time this evening to test it in 19.04 and let you know.

**Comment by kovac777** [comment]
Hm... Now I try do it on my home laptop ubuntu 19.04 and this is worked perfectly.
I have not any suggestions why it not working on my worker laptop
